version: '3.8'

services:
  emby-bot:
    build:
      context: https://github.com/Foofur83/Emby_Omby_Telegram_Bot.git
    container_name: telegram-emby-bot
    restart: unless-stopped
    volumes:
      - /mnt/Persistentstorage/Emby-Ombi_Bot:/config
      - /mnt/Persistentstorage/Emby-Ombi_Bot/data:/app/data
    environment:
      - TZ=Europe/Amsterdam
    networks:
      - default

  web-ui:
    image: foofur/emby-telegram-bot:latest
    container_name: emby-bot-webui
    restart: unless-stopped
    command: python web_ui.py
    ports:
      - "4000:4000"
    volumes:
      - /mnt/Persistentstorage/Emby-Ombi_Bot:/config
      - /mnt/Persistentstorage/Emby-Ombi_Bot/data:/app/data
      - /mnt/Persistentstorage/Emby-Ombi_Bot/templates:/app/templates
    environment:
      - TZ=Europe/Amsterdam
    networks:
      - default

networks:
  default:
    driver: bridge